"""llm_rank added to Recommendation

Revision ID: 01882a3336ca
Revises: a41bd4d0a02e
Create Date: 2026-02-28 08:00:40.639313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01882a3336ca'
down_revision: Union[str, Sequence[str], None] = 'a41bd4d0a02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('llm_rank_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'llm_rank_position')
    # ### end Alembic commands ###
