"""Fix

Revision ID: 558a09b2eb08
Revises: cf8fdaf33ef1
Create Date: 2026-02-28 20:21:13.420459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558a09b2eb08'
down_revision: Union[str, Sequence[str], None] = 'cf8fdaf33ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
