"""Add industries table and relationships

Revision ID: 6ad7c9305fc3
Revises: 8c249e7dcba2
Create Date: 2026-03-01 04:37:57.729547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad7c9305fc3'
down_revision: Union[str, Sequence[str], None] = '8c249e7dcba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('research_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_strategic_overview', sa.Text(), nullable=True),
    sa.Column('priority_initiatives', sa.Text(), nullable=True),
    sa.Column('financial_positioning', sa.Text(), nullable=True),
    sa.Column('technical_enablement_summary', sa.Text(), nullable=True),
    sa.Column('objection_handling', sa.Text(), nullable=True),
    sa.Column('strategic_roadmap_90_days', sa.Text(), nullable=True),
    sa.Column('executive_closing_statement', sa.Text(), nullable=True),
    sa.Column('executive_conversation_version', sa.Text(), nullable=True),
    sa.Column('email_version', sa.Text(), nullable=True),
    sa.Column('generated_by_llm', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('insight_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.Column('research_document_id', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['research_document_id'], ['research_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analyses', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('error_stage', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('last_research_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'companies', 'industries', ['industry_id'], ['id'])
    op.drop_column('companies', 'industry')
    op.alter_column('hpe_products', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('hpe_products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hpe_products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('hpe_products', 'business_value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('hpe_products_name_key'), 'hpe_products', type_='unique')
    op.create_index(op.f('ix_hpe_products_name'), 'hpe_products', ['name'], unique=True)
    op.add_column('insights', sa.Column('card_size', sa.String(), nullable=True))
    op.drop_column('insights', 'source_snippet')
    op.drop_column('insights', 'source_url')
    op.add_column('recommendations', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('llm_rank_position', sa.Integer(), nullable=True))
    op.add_column('recommendations', sa.Column('final_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('priority_rank', sa.Integer(), nullable=True))
    op.alter_column('recommendations', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('sales_speeches', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_speeches', 'is_current')
    op.alter_column('recommendations', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('recommendations', 'priority_rank')
    op.drop_column('recommendations', 'final_score')
    op.drop_column('recommendations', 'llm_rank_position')
    op.drop_column('recommendations', 'confidence_score')
    op.add_column('insights', sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('source_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('insights', 'card_size')
    op.drop_index(op.f('ix_hpe_products_name'), table_name='hpe_products')
    op.create_unique_constraint(op.f('hpe_products_name_key'), 'hpe_products', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('hpe_products', 'business_value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hpe_products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hpe_products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hpe_products', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.add_column('companies', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'last_research_at')
    op.drop_column('companies', 'website_url')
    op.drop_column('companies', 'industry_id')
    op.drop_column('analyses', 'error_stage')
    op.drop_column('analyses', 'error_message')
    op.drop_column('analyses', 'celery_task_id')
    op.drop_table('insight_sources')
    op.drop_table('sales_strategies')
    op.drop_table('research_documents')
    op.drop_table('industries')
    # ### end Alembic commands ###
