"""Sales Strategy models

Revision ID: ac9ca885fb92
Revises: 01882a3336ca
Create Date: 2026-02-28 10:36:18.347723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9ca885fb92'
down_revision: Union[str, Sequence[str], None] = '01882a3336ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('card_size', sa.String(), nullable=True))
    op.add_column('recommendations', sa.Column('final_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('priority_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'priority_rank')
    op.drop_column('recommendations', 'final_score')
    op.drop_column('insights', 'card_size')
    # ### end Alembic commands ###
