"""Fix

Revision ID: ad5281e43f7c
Revises: 558a09b2eb08
Create Date: 2026-02-28 20:38:40.594906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5281e43f7c'
down_revision: Union[str, Sequence[str], None] = '558a09b2eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sales_strategies', ['analysis_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_strategies', type_='unique')
    # ### end Alembic commands ###
