"""Updated Sales Strategy

Revision ID: b5694b477e62
Revises: ed81117bac9f
Create Date: 2026-02-28 12:14:03.230370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5694b477e62'
down_revision: Union[str, Sequence[str], None] = 'ed81117bac9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_strategies', sa.Column('executive_conversation_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_strategies', 'executive_conversation_version')
    # ### end Alembic commands ###
