"""AI Engine Models

Revision ID: be0c9ea54ef7
Revises: df5ac36ad638
Create Date: 2026-02-27 07:32:33.361360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0c9ea54ef7'
down_revision: Union[str, Sequence[str], None] = 'df5ac36ad638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['hpe_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.Column('research_document_id', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['research_document_id'], ['research_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analyses', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('error_stage', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('last_research_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'companies', 'industries', ['industry_id'], ['id'])
    op.drop_column('companies', 'industry')
    op.drop_column('insights', 'source_url')
    op.drop_column('insights', 'source_snippet')
    op.add_column('recommendations', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('sales_speeches', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_speeches', 'is_current')
    op.drop_column('recommendations', 'confidence_score')
    op.add_column('insights', sa.Column('source_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'last_research_at')
    op.drop_column('companies', 'industry_id')
    op.drop_column('analyses', 'error_stage')
    op.drop_column('analyses', 'error_message')
    op.drop_column('analyses', 'celery_task_id')
    op.drop_table('insight_sources')
    op.drop_table('research_documents')
    op.drop_table('product_embeddings')
    op.drop_table('industries')
    # ### end Alembic commands ###
