"""Update

Revision ID: cf8fdaf33ef1
Revises: c1bd5228bb77
Create Date: 2026-02-28 18:43:23.729307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8fdaf33ef1'
down_revision: Union[str, Sequence[str], None] = 'c1bd5228bb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('website_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'website_url')
    # ### end Alembic commands ###
