"""Fix

Revision ID: d804daae1d6e
Revises: ad5281e43f7c
Create Date: 2026-02-28 22:41:09.302021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd804daae1d6e'
down_revision: Union[str, Sequence[str], None] = 'ad5281e43f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('insight_sources_research_document_id_fkey'), 'insight_sources', type_='foreignkey')
    op.create_foreign_key(None, 'insight_sources', 'research_documents', ['research_document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insight_sources', type_='foreignkey')
    op.create_foreign_key(op.f('insight_sources_research_document_id_fkey'), 'insight_sources', 'research_documents', ['research_document_id'], ['id'])
    # ### end Alembic commands ###
