"""Product Seeder

Revision ID: ebe36c3587b5
Revises: be0c9ea54ef7
Create Date: 2026-02-27 20:24:08.365787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe36c3587b5'
down_revision: Union[str, Sequence[str], None] = 'be0c9ea54ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hpe_products', sa.Column('is_simulated', sa.Boolean(), nullable=True))
    op.add_column('hpe_products', sa.Column('embedding_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hpe_products', 'embedding_hash')
    op.drop_column('hpe_products', 'is_simulated')
    # ### end Alembic commands ###
