"""SalesStrategy 2

Revision ID: ed81117bac9f
Revises: cf49f1c3a28f
Create Date: 2026-02-28 11:56:09.125011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed81117bac9f'
down_revision: Union[str, Sequence[str], None] = 'cf49f1c3a28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_strategic_overview', sa.Text(), nullable=True),
    sa.Column('priority_initiatives', sa.Text(), nullable=True),
    sa.Column('financial_positioning', sa.Text(), nullable=True),
    sa.Column('technical_enablement_summary', sa.Text(), nullable=True),
    sa.Column('objection_handling', sa.Text(), nullable=True),
    sa.Column('strategic_roadmap_90_days', sa.Text(), nullable=True),
    sa.Column('executive_closing_statement', sa.Text(), nullable=True),
    sa.Column('email_version', sa.Text(), nullable=True),
    sa.Column('generated_by_llm', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_strategies')
    # ### end Alembic commands ###
